spring:
  application:
    name: car-service
  kafka:
    topic:
      name: car_topic
    bootstrap-servers: ${eureka.instance.hostname}:9092

  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/auto-sharing
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"

server:
  port: 8073

eureka:
  instance:
    hostname: localhost
    port: 8071
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

info:
  app:
    name: ${spring.application.name}