spring:
  application:
    name: car-service

  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/auto-sharing
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"

server:
  port: 8091

eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

info:
  app:
    name: ${spring.application.name}