spring:
  application:
    name: car-service

server:
  port: 8091

eureka:
  instance:
    hostname: localhost
    port: 8081
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

info:
  app:
    name: ${spring.application.name}