spring:
  application:
    name: car-service
  kafka:
    topic:
      name:
        car: car_topic
        order: order_topic
    bootstrap-servers: ${eureka.instance.hostname}:9092
    properties:
      schema.registry.url: http://localhost:8071

  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/auto-sharing
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"

server:
  port: 8073

eureka:
  instance:
    hostname: localhost
    port: 8071
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka

info:
  app:
    name: ${spring.application.name}