spring:
  application:
    name: car-service

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}